apiVersion: v1
kind: Service
metadata:
  name: simpload-service
spec:
  type: NodePort
  selector:
    app: simpload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpload
  template:
    metadata:
      labels:
        app: simpload
    spec:
      containers:
        - name: simpload
          image: korpenter/simpload:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
        - name: python-sidecar
          image: korpenter/sidecarr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TUS_SERVER_URL
              value: "${TUS_SERVER_URL}"
          ports:
            - containerPort: 5000
